### ISSUE TITLE
fracture propagation in elastic materials

### ISSUE THREAD

**Issue by BinWang0213** [Franjcf/hybridBiotInterFoam#3]
Hi,

Thanks for your great library and sharing with the community.

I noticed that all fluid-driven cases are plastic material. Can we model the fracture propagation process in the elastic material?
How can we prescribe the stress intensity factors for the solid material?

Such as KGD model:
![image](https://user-images.githubusercontent.com/20053787/118567025-a9d18980-b73a-11eb-97a1-83a033908141.png)
https://onlinelibrary.wiley.com/doi/10.1002/nag.2557

I try to modify the case of `fracture_wellbore_pressure`, but it seems can not solve the solid mechanics part.

Here is the case file:
[fracture_wellbore_pressure.zip](https://github.com/Franjcf/hybridBiotInterFoam/files/6497357/fracture_wellbore_pressure.zip)

Thanks,
Bin

**Comment by Franjcf** [comment]
Dear Bin,

Thanks for your inquiry.

So far I have not implemented fracture propagation in elastic materials. I took a look at the paper that you sent me and came down with the following thoughts that may be helpful:

In hybridBiotInterFoam fracture propagation is not defined by the  "generation of new surfaces” in the mesh. Instead, new fractures are created by the advection of the solid fraction field (i.e. the epss field in OpenFOAM). This allows us to create fractures without the need of initializing a “nucleating fracture” at the beginning of the simulations. In the downside, this makes the implementation of elasticly-driven fractures a more complicated task. To the best of my knowledge, linear elastic mechanics should not be able to model fractures just by themselves, as they are restricted to the “quasi-static” regime, where deformations are very small. The paper you referenced is able to remove this limitation by imposing a yield criterion that affects the mesh itself and is separate from linear-elastic solution (a very clever approach). I hypothesize that you may be able to implement a similar yield criterion based on the implemented linear-elastic equations within hybridBiotInterFoam. This would be done by moving the solid fraction field by 1 cell in the direction of the “maximum principle stress” whenever said criterion is met. To do that I would take a look and modify epssEq.H and the solidMechanics.H files in the elasticHBIF solver. This obviously needs some more thought, but I think that would make for a really nice investigation.

Please let me know if you have any questions. 
Francisco

**Comment by BinWang0213** [comment]
Hi Fancisco,

Thanks for your detailed explanations.

I know there are few approaches that are used in hydraulic fracturing simulation:

1. Surface Generation method. Fracture is explicitly represented by mesh interfaces.  
    https://onlinelibrary.wiley.com/doi/10.1002/nag.2557
2. XFEM method. Fracture is explicitly handled by enriched FEM elements.
    https://doi.org/10.1007/s11440-019-00813-x
3. Phase-field damage method. Fractures are implicitly represented by a scalar field (similar to your work here).
    https://doi.org/10.1002/2017JB014740
4. Peridynamics method. A mesh-less method that fractures are represented by breaking-bonds.
    https://doi.org/10.1016/j.cma.2020.113101

Based on my understanding, Methods 1-2 are quite challenging to deal with fracture branching and 3D implementation due to it requires to track fracture.  Method 3-4 are relatively new but it overcomes the limitation of Methods 1-2 in nature. 

I found your work is similar to the Phase-field method but even better due to the generalization of Darcy and Stokes equation. Also, this is implemented in OpenFOAM. So we can easily run a large 3D problem. 

To implement the fracture propagation in elastic materials, I think that I need to start from a simple pressurized Fracture problem without propagation. See Section 3.2 @ https://doi.org/10.1002/2017JB014740
![image](https://user-images.githubusercontent.com/20053787/118733666-51fe5580-b802-11eb-84b4-770178d4b826.png)

Can we reproduce the results above using the existing code?

BTW, I think I should able to run the fracture_wellbore_pressure case using elasticHBIF even without propagation. Could you help me to see is there any problem with my setup?
https://github.com/Franjcf/hybridBiotInterFoam/files/6497357/fracture_wellbore_pressure.zip

Also, how can we output the stress field?

Thanks,
Bin

**Comment by Franjcf** [comment]
Hi Bin,

I think it should be possible to replicate the results from Section 3.2 from the problem you sent me. The model should satisfy all the assumptions: "homogeneous and isotropic, with linear stress-strain dependence, isothermal conditions, and plane and infinitesimal strains". However I still think you would need to implement some sort of phase-field "advection" mechanism to capture changes in the fracture aperture as a function of different inputs. 

Nevertheless, I would try to set up the problem without any changes in the code to see how the displacement vector "d" and the pressure profiles look for different experimental conditions.

The stress field "sigma" is calculated in the calculateStress.H file in the elasticHBIF solver. Note that this is a tensor. You can get a scalar value for the vonMiss stresses by looking at the sigmaEq field. You can output them by changing their IO object properties. 

I will take a look at your simulation setup once I have a little more time. In the meantime I would consider the following:  Sometimes the model becomes unstable if the associated elastic deformations are very large or very sudden, this is due to the non-linear nature of the coupling and the quasi-static assumptions of the linear-elastic model. In my experience, instabilities can be caused by large flows through the porous media or very large pressures. Time stepping can also be a factor. 

Best,
Francisco

**Comment by BinWang0213** [comment]
Hi Fancisco,

Thanks a lot for your help. It will be very helpful if you can set up a Sneddon problem to start with.

After reading more materials of the phase-field method, I believe the implementation of the phase-field "advection"  will be the implementation of Eq. 42 [1]:
![image](https://user-images.githubusercontent.com/20053787/118909620-e5aa5180-b8e8-11eb-93e1-c325eb801c9d.png)
where 
* `d` is the damage field, d=1 fracture, d=0 solid. This is similar to `epss`
* `g_c` is the critical energy release rate to control the failure criterion
* `l` is the thickness of the damage field
* `H+` is the so-called history variable field to make sure we have irreversibility of the fracture process.
   It is not quite clear how to compute this. 

Also, Eq. 41 [1] of linear elastic eqn is slightly modified to couple with the damage field.
![image](https://user-images.githubusercontent.com/20053787/118910787-b399ef00-b8ea-11eb-95a2-73c16e58dc26.png)
![image](https://user-images.githubusercontent.com/20053787/118911850-7df60580-b8ec-11eb-9e7e-4d9cd49f03fd.png)
where 
* `alpha` is the biot coefficient

So I need to:
 (1) modify the Eq. 29 of your paper [2] based on Eq. 41 [1] 
 (2) implement Eq. 42 [1] to advect damage field

Do you have any quick idea about the above statements?

I don't have hands-on experience with OpenFOAM programming, do you think this could be easily added to your framework?

Ref:
[1] Phase Field Model of Hydraulic Fracturing in Poroelastic Media: Fracture Propagation, Arrest, and Branching Under Fluid Injection and Extraction. https://doi.org/10.1002/2017JB014740
[2] Modeling Multiphase Flow Within and Around Deformable Porous Materials: A Darcy-Brinkman-Biot Approach
.https://doi.org/10.1029/2020WR028734

Thanks,
Bin

**Comment by Franjcf** [comment]
Hi Bin,

I think the application of these equations into the model is definitely doable by following the steps that you outlined. From what you have shared with me and what I have read in the literature, there is no reason why you could not combine the Darcy-Brinkman approach with a phase-field fracturing approach. However, this also constitutes a non-trivial amount of work (between implementation, testing, and validation). In my opinion, such an investigation would be of great interest and worthy of publication. Unfortunately, I currently don't have the time to work or set up such a project (I am graduating very soon). I am sorry about that. 

Nevertheless, I can definitely help with questions that you may have regarding the implementation of the solver and the validity of the equations. If you are interested in modifying and creating your own custom version of the code I would recommend the following OpenFOAM tutorial (it is how I started programing in OpenFOAM): https://www.cypriensoulaine.com/openfoam. Cyprien Soulaine (the author of this tutorial) will also be giving an online training at Interpore if you are interested: https://www.interpore.org/interpore-online-short-course-cyprien-soulaine-introduction-to-open-source-computational-fluid-dynamics-using-openfoam-technology/

Best,
Francisco

**Comment by BinWang0213** [comment]
Hi Francisco,

I really appreciate your help. I am graduating soon as well. 

This is a project that I may look at in the next year. I may have some trouble regarding the implementation and deriving the equations. Your statement about combining the Darcy-Brinkman approach with a phase-field fracturing approach is really encouraging. 

But as you said, this is a non-trivial task I will look at this back later on. Hoping we can have some collaborations via extending your great library here.

Thanks,
Bin
